version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  chromadb:
    image: ghcr.io/chroma-core/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: neo4j-budget
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/passw0rd
    volumes:
      - ./neo4j-import:/import
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data:
